name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    name: install-pip-deps
    runs-on: self-hosted
    
    steps:
      - name: Clone python-greetings
        uses: actions/checkout@v3.5.2
        with:
          repository: mtararujs/python-greetings
        
      - name: Install dependencies
        run: pip install -r requirements.txt
        
  deploy-to-dev:
    name: deploy-to-dev
    runs-on: self-hosted
    needs: install-pip-deps
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy-to-dev

      - name: deploy-to-dev
        run: echo Deploying to the dev environment...
        
  tests-on-dev:
    name: tests-on-dev
    runs-on: self-hosted
    needs: deploy-to-dev
    
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests-on-dev

      - name: tests-on-dev
        run: echo Testing the dev environment...
        
  deploy-to-staging:
      name: deploy-to-staging
      runs-on: self-hosted
      needs: tests-on-dev
    
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/deploy-to-staging

        - name: deploy-to-staging
          run: echo Deploying to staging...
          
  tests-on-staging:
      name: tests-on-staging
      runs-on: self-hosted
      needs: deploy-to-staging
    
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/tests-on-staging

        - name: tests-on-staging
          run: echo Tests on staging...
        
  deploy-to-preprod:
      name: deploy-to-preprod
      runs-on: self-hosted
      needs: tests-on-staging
    
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/ deploy-to-preprod

        - name: deploy-to-preprod
          run: echo Deploying to pre-production...
        
  tests-on-preprod:
      name: tests-on-preprod
      runs-on: self-hosted
      needs:  deploy-to-preprod
    
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/tests-on-preprod

        - name: tests-on-preprod
          run: echo Testing the pre-production...
        
  deploy-to-prod:
      name: deploy-to-prod
      runs-on: self-hosted
      needs: tests-on-preprod
    
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/deploy-to-prod

        - name: deploy-to-prod
          run: echo Deploying to production...
        
  tests-on-prod:
      name: tests-on-prod
      runs-on: self-hosted
      needs: deploy-to-prod
    
      steps:
        - uses: actions/checkout@v4
        - uses: ./.github/actions/tests-on-prod

        - name: tests-on-prod
          run: echo Testing the production...
          
Update python-greetings.yml · BunnyBaklazan/TheFirstOne@2dbdfd5
